
server:
    port: 8081
    servlet:
        context-path: /interceptor

logging:
  level:
    org.springframework: ERROR
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  file:
    name: /home/ubuntu/openfire-logs.log
